version: '3'
services:
  user_management:
    image: user_management_image:latest
    ports:
      - "8000:8000"
    networks:
      - server-side-stream
  stream_management:
    image: stream_management_image:latest
    ports:
      - "3001:3001"
    networks:
      - server-side-stream
  api_gateway:
    image: api_gateway_image:latest
    ports:
      - "8006:8006"
    networks:
      - server-side-stream

networks:
  server-side-stream:
    driver: bridge
