version: '3'
services:
  api_gateway:
    build: ./API_GATEWAY
    image: api_gateway_image
    ports:
      - "8006:8006"
    networks:
      - microservices-network

  stream_management:
    build: ./streamManagement
    image: stream_management_image
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  user_management:
    build: ./userManagement
    image: user_management_image
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"      
      - "15673:15672"    
    networks:
      - microservices-network

  comment_service:
    build:
      context: ./commentManagement/commentService
    image: comment_service_image
    ports:
      - "8005:8005"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
